-- create 테이블

-- =========================
-- 0) ENUM TYPES
-- =========================
CREATE TYPE member_st_enum AS ENUM ('JOIN', 'BAN');
CREATE TYPE book_st_enum AS ENUM ('NEW', 'LIKE_NEW', 'GOOD', 'USED');
CREATE TYPE sale_st_enum AS ENUM ('SALE', 'RESERVED', 'SOLD');
CREATE TYPE settlement_st_enum AS ENUM ('WAIT', 'COMPLETE');
CREATE TYPE request_st_enum AS ENUM ('WAIT', 'APPROVED', 'REJECTED');
CREATE TYPE oauth_provider_enum AS ENUM ('KAKAO', 'NAVER');
CREATE TYPE join_st_enum AS ENUM ('WAIT', 'JOINED', 'REJECTED', 'LEFT', 'KICKED');

-- =========================
-- 1) TABLES
-- =========================

CREATE TABLE "MEMBER_INFO" (
  "MEMBER_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "LOGIN_ID" VARCHAR(50) NOT NULL,
  "MEMBER_PWD" VARCHAR(255) NOT NULL,
  "MEMBER_EMAIL" VARCHAR(100) NOT NULL,
  "MEMBER_TEL_NO" VARCHAR(20) NULL,
  "MEMBER_NICKNM" VARCHAR(50) NOT NULL,
  "MEMBER_DELETED_DTM" TIMESTAMP NULL,
  "MEMBER_LAST_LOGIN_DTM" TIMESTAMP NULL,
  "MEMBER_ST" member_st_enum NOT NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPD_DTM" TIMESTAMP NULL
);

CREATE TABLE "ADDRESS_INFO" (
  "ADDR_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "MEMBER_SEQ" BIGINT NOT NULL,
  "POST_NO" VARCHAR(10) NOT NULL,
  "ADDR_H" VARCHAR(200) NOT NULL,
  "ADDR_D" VARCHAR(200) NOT NULL,
  "DEFAULT_YN" SMALLINT NOT NULL,
  "ADDR_NM" VARCHAR(50) NOT NULL
);

CREATE TABLE "BOOK_IMAGE" (
  "BOOK_IMG_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "IMG_URL" VARCHAR(500) NOT NULL,
  "SORT_SEQ" BIGINT NULL
);

CREATE TABLE "CATEGORY" (
  "CATEGORY_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "CATEGORY_NM" VARCHAR(50) NOT NULL,
  "CATEGORY_SORT_SEQ" BIGINT NULL,
  "CRT_DTM" TIMESTAMP NOT NULL,
  "UPD_DTM" TIMESTAMP NULL
);

CREATE TABLE "BOOK_INFO" (
  "BOOK_INFO_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "ISBN" VARCHAR(20) NOT NULL,
  "BOOK_TITLE" VARCHAR(200) NOT NULL,
  "BOOK_AUTHOR" VARCHAR(100) NULL,
  "BOOK_PUBLISHER" VARCHAR(100) NULL,
  "BOOK_IMG" VARCHAR(500) NULL,
  "BOOK_ORG_PRICE" INT NULL
);

CREATE TABLE "SB_TRADE_INFO" (
  "TRADE_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "MEMBER_SELLER_SEQ" BIGINT NOT NULL,
  "SALE_TITLE" VARCHAR(200) NOT NULL,
  "BOOK_ST" book_st_enum NOT NULL,
  "SALE_CONT" TEXT NULL,
  "SALE_PRICE" INT NOT NULL,
  "BOOK_DELIVERY_COST" INT NULL,
  "SALE_REGION_NM" VARCHAR(100) NULL,
  "SALE_ST" sale_st_enum NOT NULL,
  "SALE_ST_DTM" TIMESTAMP NULL,
  "VIEWS" BIGINT DEFAULT 0 NOT NULL,
  "WISH_CNT" BIGINT DEFAULT 0 NOT NULL,
  "BOOK_SALE_DTM" TIMESTAMP NULL,
  "POST_NO" VARCHAR(10) NOT NULL,
  "ADDR_H" VARCHAR(200) NOT NULL,
  "ADDR_D" VARCHAR(200) NOT NULL,
  "RECIPIENT_PH_NO" VARCHAR(20) NOT NULL,
  "RECIPIENT_NM" VARCHAR(50) NOT NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPD_DTM" TIMESTAMP NULL,
  "PAYMENT_TYPE" VARCHAR(20) NOT NULL,
  "BOOK_INFO_SEQ" BIGINT NOT NULL,
  "CATEGORY_SEQ" BIGINT NOT NULL,
  "BOOK_IMG_SEQ" BIGINT NOT NULL,
  "MEMBER_BUYER_SEQ" BIGINT NOT NULL
);

CREATE TABLE "CHATROOM" (
  "CHAT_ROOM_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "TRADE_SEQ" BIGINT NOT NULL,
  "LAST_MSG_DTM" TIMESTAMP NULL,
  "LAST_MSG" TEXT NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
  "MEMBER_BUYER_SEQ" BIGINT NOT NULL
);

CREATE TABLE "CHAT_MSG" (
  "CHAT_MSG_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "CHAT_ROOM_SEQ" BIGINT NOT NULL,
  "TRADE_SEQ" BIGINT NOT NULL,
  "CHAT_CONT" TEXT NULL,
  "SENT_DTM" TIMESTAMP NULL,
  "READ_YN" BOOLEAN NULL
);

CREATE TABLE "SETTLEMENT" (
  "SETTLEMENT_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "MEMBER_SELLER_SEQ" BIGINT NOT NULL,
  "MEMBER_BUYER_SEQ" BIGINT NOT NULL,
  "SALE_PRICE" BIGINT NOT NULL,
  "SETTLEMENT_ST" settlement_st_enum NOT NULL,
  "CRT_DTM" TIMESTAMP NOT NULL,
  "TRADE_SEQ" BIGINT NOT NULL
);

CREATE TABLE "TRADE_WISH" (
  "TRADE_WISH_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "TRADE_SEQ" BIGINT NOT NULL,
  "MEMBER_SEQ" BIGINT NOT NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "ALARM" (
  "ALARM_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "SENT_DTM" TIMESTAMP NULL,
  "ALARM_CONT" VARCHAR(500) NULL,
  "CHAT_MSG_SEQ" BIGINT NOT NULL,
  "CHAT_ROOM_SEQ" BIGINT NOT NULL,
  "TRADE_SEQ" BIGINT NOT NULL,
  "MEMBER_SEQ" BIGINT NOT NULL
);

CREATE TABLE "REPORT" (
  "REPOST_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "MEMBER_SEQ" BIGINT NOT NULL,
  "REPORT_TITLE" VARCHAR(200) NULL,
  "REPORT_CONT" TEXT NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "REPORT_IMG_URL" VARCHAR(500) NULL
);

CREATE TABLE "ADMIN" (
  "ADMIN_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "ADMIN_LOGIN_ID" VARCHAR(50) NOT NULL,
  "ADMIN_PASSWORD" VARCHAR(255) NOT NULL
);

CREATE TABLE "LOGIN_INFO" (
  "LOGIN_INFO_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "ADMIN_SEQ" BIGINT NOT NULL,
  "LOGIN_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
  "LOGIN_IP" VARCHAR(45) NULL,
  "LOGOUT_DTM" TIMESTAMP NULL
);

CREATE TABLE "NOTICE" (
  "NOTICE_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "ADMIN_SEQ" BIGINT NOT NULL,
  "NOTICE_TITLE" VARCHAR(200) NULL,
  "NOTICE_CONT" TEXT NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPD_DTM" TIMESTAMP NULL
);

CREATE TABLE "BOOK_CLUB" (
  "BOOK_CLUB_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "BOOK_CLUB_NAME" VARCHAR(100) NOT NULL,
  "BOOK_CLUB_DESC" TEXT NULL,
  "BOOK_CLUB_RG" VARCHAR(50) NULL,
  "BOOK_CLUB_MAX_MEMBER" INT NULL,
  "BOOK_CLUB_DELETED_DT" DATE NULL,
  "BANNER_IMG_URL" VARCHAR(500) NULL,
  "BOOK_CLUB_SCHEDULE" VARCHAR(200) NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPD_DTM" TIMESTAMP NULL,
  "BOOK_CLUB_LEADER_SEQ" BIGINT NOT NULL
);

CREATE TABLE "BOOK_CLUB_WISH" (
  "BOOK_CLUB_WISH_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "BOOK_CLUB_SEQ" BIGINT NOT NULL,
  "CRT_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "MEMBER_SEQ" BIGINT NOT NULL
);

CREATE TABLE "BOOK_CLUB_REQUEST" (
  "BOOK_CLUB_REQUEST_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "BOOK_CLUB_SEQ" BIGINT NOT NULL,
  "REQUEST_CONT" TEXT NULL,
  "REQUEST_ST" request_st_enum NOT NULL,
  "REQUEST_DTM" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "REQUEST_PROCESSED_DT" DATE NULL,
  "REQUEST_MEMBER_SEQ" BIGINT NOT NULL
);

CREATE TABLE "BOOK_CLUB_MEMBER" (
  "BOOK_CLUB_MEMBER_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "BOOK_CLUB_SEQ" BIGINT NOT NULL,
  "LEADER_YN" BOOLEAN NOT NULL,
  "JOIN_ST" join_st_enum NULL,
  "JOIN_ST_UPDATE_DTM" TIMESTAMP NULL,
  "MEMBER_SEQ" BIGINT NOT NULL
);

CREATE TABLE "BOOK_CLUB_BOARD" (
  "BOOK_CLUB_BOARD_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "BOOK_CLUB_SEQ" BIGINT NOT NULL,
  "BOARD_TITLE" VARCHAR(200) NULL,
  "BOARD_CONT" TEXT NULL,
  "BOARD_IMG_URL" VARCHAR(500) NULL,
  "BOARD_DELETED_YN" BOOLEAN NULL,
  "BOARD_DELETED_DTM" TIMESTAMP NULL,
  "PARENT_BOOK_CLUB_BOARD_SEQ" BIGINT NOT NULL,
  "BOOK_CLUB_SEQ2" BIGINT NOT NULL,
  "MEMBER_SEQ" BIGINT NOT NULL,
  "BOOK_INFO_SEQ" BIGINT NOT NULL
);

CREATE TABLE "MEMBER_OAUTH" (
  "MEMBER_OAUTH_SEQ" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "PROVIDER" oauth_provider_enum NULL,
  "CONNECTED_DT" DATE NULL,
  "MEMBER_SEQ" BIGINT NOT NULL
);

-- =========================
-- 2) CONSTRAINTS (PK)
-- =========================

ALTER TABLE "ADDRESS_INFO" ADD CONSTRAINT "PK_ADDRESS_INFO" PRIMARY KEY ("ADDR_SEQ","MEMBER_SEQ");
ALTER TABLE "BOOK_IMAGE" ADD CONSTRAINT "PK_BOOK_IMAGE" PRIMARY KEY ("BOOK_IMG_SEQ");
ALTER TABLE "SETTLEMENT" ADD CONSTRAINT "PK_SETTLEMENT" PRIMARY KEY ("SETTLEMENT_SEQ");
ALTER TABLE "CHATROOM" ADD CONSTRAINT "PK_CHATROOM" PRIMARY KEY ("CHAT_ROOM_SEQ","TRADE_SEQ");
ALTER TABLE "SB_TRADE_INFO" ADD CONSTRAINT "PK_SB_TRADE_INFO" PRIMARY KEY ("TRADE_SEQ");
ALTER TABLE "MEMBER_INFO" ADD CONSTRAINT "PK_MEMBER_INFO" PRIMARY KEY ("MEMBER_SEQ");
ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("CATEGORY_SEQ");
ALTER TABLE "TRADE_WISH" ADD CONSTRAINT "PK_TRADE_WISH" PRIMARY KEY ("TRADE_WISH_SEQ");
ALTER TABLE "BOOK_INFO" ADD CONSTRAINT "PK_BOOK_INFO" PRIMARY KEY ("BOOK_INFO_SEQ");
ALTER TABLE "CHAT_MSG" ADD CONSTRAINT "PK_CHAT_MSG" PRIMARY KEY ("CHAT_MSG_SEQ","CHAT_ROOM_SEQ","TRADE_SEQ");
ALTER TABLE "ALARAM" ADD CONSTRAINT "PK_ALARAM" PRIMARY KEY ("ALARM_SEQ");
ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY ("REPOST_SEQ","MEMBER_SEQ");
ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY ("ADMIN_SEQ");
ALTER TABLE "LOGIN_INFO" ADD CONSTRAINT "PK_LOGIN_INFO" PRIMARY KEY ("LOGIN_INFO_SEQ","ADMIN_SEQ");
ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_SEQ","ADMIN_SEQ");
ALTER TABLE "BOOK_CLUB" ADD CONSTRAINT "PK_BOOK_CLUB" PRIMARY KEY ("BOOK_CLUB_SEQ");
ALTER TABLE "BOOK_CLUB_WISH" ADD CONSTRAINT "PK_BOOK_CLUB_WISH" PRIMARY KEY ("BOOK_CLUB_WISH_SEQ","BOOK_CLUB_SEQ");
ALTER TABLE "BOOK_CLUB_REQUEST" ADD CONSTRAINT "PK_BOOK_CLUB_REQUEST" PRIMARY KEY ("BOOK_CLUB_REQUEST_SEQ","BOOK_CLUB_SEQ");
ALTER TABLE "BOOK_CLUB_MEMBER" ADD CONSTRAINT "PK_BOOK_CLUB_MEMBER" PRIMARY KEY ("BOOK_CLUB_MEMBER_SEQ","BOOK_CLUB_SEQ");
ALTER TABLE "BOOK_CLUB_BOARD" ADD CONSTRAINT "PK_BOOK_CLUB_BOARD" PRIMARY KEY ("BOOK_CLUB_BOARD_SEQ","BOOK_CLUB_SEQ");
ALTER TABLE "MEMBER_OAUTH" ADD CONSTRAINT "PK_MEMBER_OAUTH" PRIMARY KEY ("MEMBER_OAUTH_SEQ");

-- =========================
-- 3) EXTRA UNIQUE (필수)
--    CHATROOM 복합PK인데, CHAT_MSG가 단독 FK로 참조하므로 UNIQUE 필요
-- =========================
ALTER TABLE "CHATROOM" ADD CONSTRAINT "UQ_CHATROOM_CHAT_ROOM_SEQ" UNIQUE ("CHAT_ROOM_SEQ");
ALTER TABLE "CHATROOM" ADD CONSTRAINT "UQ_CHATROOM_TRADE_SEQ" UNIQUE ("TRADE_SEQ");

-- =========================
-- 4) FOREIGN KEYS (원본 구조 유지)
-- =========================

ALTER TABLE "ADDRESS_INFO"
  ADD CONSTRAINT "FK_MEMBER_INFO_TO_ADDRESS_INFO_1"
  FOREIGN KEY ("MEMBER_SEQ")
  REFERENCES "MEMBER_INFO" ("MEMBER_SEQ");

ALTER TABLE "CHATROOM"
  ADD CONSTRAINT "FK_SB_TRADE_INFO_TO_CHATROOM_1"
  FOREIGN KEY ("TRADE_SEQ")
  REFERENCES "SB_TRADE_INFO" ("TRADE_SEQ");

ALTER TABLE "CHAT_MSG"
  ADD CONSTRAINT "FK_CHATROOM_TO_CHAT_MSG_1"
  FOREIGN KEY ("CHAT_ROOM_SEQ")
  REFERENCES "CHATROOM" ("CHAT_ROOM_SEQ");

ALTER TABLE "CHAT_MSG"
  ADD CONSTRAINT "FK_CHATROOM_TO_CHAT_MSG_2"
  FOREIGN KEY ("TRADE_SEQ")
  REFERENCES "CHATROOM" ("TRADE_SEQ");

ALTER TABLE "REPORT"
  ADD CONSTRAINT "FK_MEMBER_INFO_TO_REPORT_1"
  FOREIGN KEY ("MEMBER_SEQ")
  REFERENCES "MEMBER_INFO" ("MEMBER_SEQ");

ALTER TABLE "LOGIN_INFO"
  ADD CONSTRAINT "FK_ADMIN_TO_LOGIN_INFO_1"
  FOREIGN KEY ("ADMIN_SEQ")
  REFERENCES "ADMIN" ("ADMIN_SEQ");

ALTER TABLE "NOTICE"
  ADD CONSTRAINT "FK_ADMIN_TO_NOTICE_1"
  FOREIGN KEY ("ADMIN_SEQ")
  REFERENCES "ADMIN" ("ADMIN_SEQ");

ALTER TABLE "BOOK_CLUB_WISH"
  ADD CONSTRAINT "FK_BOOK_CLUB_TO_BOOK_CLUB_WISH_1"
  FOREIGN KEY ("BOOK_CLUB_SEQ")
  REFERENCES "BOOK_CLUB" ("BOOK_CLUB_SEQ");

ALTER TABLE "BOOK_CLUB_REQUEST"
  ADD CONSTRAINT "FK_BOOK_CLUB_TO_BOOK_CLUB_REQUEST_1"
  FOREIGN KEY ("BOOK_CLUB_SEQ")
  REFERENCES "BOOK_CLUB" ("BOOK_CLUB_SEQ");

ALTER TABLE "BOOK_CLUB_MEMBER"
  ADD CONSTRAINT "FK_BOOK_CLUB_TO_BOOK_CLUB_MEMBER_1"
  FOREIGN KEY ("BOOK_CLUB_SEQ")
  REFERENCES "BOOK_CLUB" ("BOOK_CLUB_SEQ");

ALTER TABLE "BOOK_CLUB_BOARD"
  ADD CONSTRAINT "FK_BOOK_CLUB_TO_BOOK_CLUB_BOARD_1"
  FOREIGN KEY ("BOOK_CLUB_SEQ")
  REFERENCES "BOOK_CLUB" ("BOOK_CLUB_SEQ");

