

-- 판매글 상세 조회
SELECT
    ,sb.CATEGORY_NM
    ,sb.BOOK_DELIVERY_COST
    ,sb.BOOK_ST
    ,sb.SALE_RG
    ,sb.SALE_CONT
    ,sb.SELLER_NM
    ,sb.CRT_DTM
    ,sb.SALE_TITLE
    ,b.BOOK_TITLE
    ,b.BOOK_AUTHOR
    ,b.BOOK_PUBLISHER
    ,b.BOOK_ORG_PRICE
    ,b.BOOK_IMG
FROM SB_TRADE_INFO AS sb
JOIN BOOK_INFO AS b
ON sb.BOOK_SEQ = b.BOOK_SEQ
JOIN BOOK_IMAGE AS i
ON sb.TRADE_SEQ = i.TRADE_SEQ
WHERE sb.TRADE_SEQ = #{tradeSeq}

SELECT IMG_URL
FROM BOOK_IMAGE
WHERE TRADE_SEQ = #{tradeSeq}
